### ISSUE TITLE
Malformed FAT exceptions

### ISSUE THREAD

**Issue by McSpidey** [mdsteele/rust-cfb#1]
Hi

Firstly thanks for creating this excelent library!

I'm new to Rust but have been testing this library on a variety of files and found for a significant number of .max files (3dsmax uses CompoundFiles) it gives an error on otherwise known good files  where the entries and sectors are off by 1, triggering a Malformed FAT error.

Example: 
"{ kind: InvalidData, error: StringError("Malformed FAT (FAT has 26051 entries, but file has only 26050 sectors)") }', src\libcore\result.rs:997:5"

Oddly I can't get some other CompoundFile libraries I've tried with Python or C# to crash with these same sample compound files. The only correlation I've managed to find so far is the likelihood of these failing validation appears to go up with the file size. The smallest I've managed to get it to trigger the error on so far is 101MB, but I'm unsure if that plays any part.

Any assistance or tips would be appreciated :)

**Comment by mdsteele** [comment]
Thanks for the report!  It's possible that `rust-cfb` is being too strict here; there are certain other file format checks that `rust-cfb` used to have (based on my reading of the format spec), until I found examples of known good files that didn't obey those checks, so I had to relax them.

It would be interesting to know what that last extra FAT entry is.  Could you try modifying `rust-cfb/src/internal/alloc.rs` to put e.g. `println!("Last FAT entry is {}", self.fat[self.fat.len()-1]);` right before the `"FAT has {} entries, but file has only {} sectors"` check in `validate()` and see what you get?

**Comment by McSpidey** [comment]
I get this.

Last FAT entry is 4294967294

**Comment by McSpidey** [comment]
I tested bypassing that malformed!() call alltogether and the file appeared to load ok, however parsing the contents of a stream to completion eventually lead to this error.

thread 'main' panicked at 'assertion failed: sector_id < self.num_sectors', libs\cfb\src\internal\sector.rs:53:9

**Comment by McSpidey** [comment]
I bypassed both validate() in alloc.rs and the ascert at line 53 in sectors.rs and the file parses fully without error.

This line.
        // debug_assert!(sector_id < self.num_sectors);

**Comment by mdsteele** [comment]
> Last FAT entry is 4294967294

Thanks.  `4294967294` is `0xfffffffe`, which is the `END_OF_CHAIN` constant, which means that that sector is the last sector in its particular stream.  So, hmm, there's some stream in the file whose last sector isn't actually in the file?

The [CFB spec](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-cfb/53989ce4-7b05-4f8d-829b-d08d6148375b) is pretty unambiguous on this point: "If the last FAT sector contains an entry FAT[N] != FREESECT (0xFFFFFFFF), the file size MUST be at least (N + 1) x (Sector Size) bytes in length."  (In other words, N sectors plus the header.)  However, I've previously learned the hard way that the CFB spec doesn't always match reality.  /-:

Looking at [`src/lib.rs:496`](https://github.com/mdsteele/rust-cfb/blob/31ba871/src/lib.rs#L496), it looks like `rust-cfb` counts the number of sectors by dividing the file size by the sector size and rounding _down_.  I wonder: maybe that last sector _is_ partially present in your file, up until the end of its stream data, and the program that generated the file didn't bother to pad out that last sector to make the file size a multiple of the sector size (which is reasonable, even though it's not what the spec says).  If that's what's going on, then `rust-cfb` should be changed to handle that case.

Could you check the exact size of your CFB file in bytes, and also the size of that stream in bytes (the one that crashes if you don't comment out the assert in `sector.rs:53`)?  That should hopefully give us some clues.

**Comment by mdsteele** [comment]
Hmmmm, actually, now that I think about it again, I realize I may have misunderstood the spec:

> "If the last FAT sector contains an entry FAT[N] != FREESECT (0xFFFFFFFF), the file size MUST be at least (N + 1) x (Sector Size) bytes in length."

If "FAT[N]" in that quote is zero-based-indexed, and the FAT has, say, 5 entries (so FAT[4] is the last non-free entry), then N=4, and the file size must be at least (4 + 1) x (Sector Size).  That's one full sector for the header, and 4 full sectors for the first four FAT entries, and then the last FAT entry could correspond to a partial sector at the end of the file.

So if we can confirm that that's what's going on, then `rust-cfb` is definitely wrong here.

Weird though that that would only happen with large files?

**Comment by McSpidey** [comment]
CFB total file size (from windows explorer properties)
101 MB (106,705,932 bytes)

Stream size as seen from your rust-cfb's length (I'll need to find or make another external tool to veriy this)
stream.len() = 25612.

The size factor may be a misnomer, it could be the source version software that made it (I'm looking for more and varied samples to try and see how the broken ones are made).

**Comment by McSpidey** [comment]
I used OpenMCD's viewer (https://sourceforge.net/projects/openmcdf/files/Sample%20Compound%20File%20Viewer/ ...not the most stable tool for me) and it also confirmed, this stream is 25612 bytes.

**Comment by McSpidey** [comment]
It sees the contents as follows.
![image](https://user-images.githubusercontent.com/1709573/57309229-0a309800-712b-11e9-8e4e-d2583cfe98db.png)

**Comment by McSpidey** [comment]
Just found out by 7zip can see these streams.
Small working one on the left, crashing one on the right.
![image](https://user-images.githubusercontent.com/1709573/57309932-47e1f080-712c-11e9-8396-aefc07c4e3bd.png)

and how 7zip sees the file sizes for each.
![image](https://user-images.githubusercontent.com/1709573/57310024-6c3dcd00-712c-11e9-85bb-a29a96fab4a9.png)

**Comment by McSpidey** [comment]
Oh nice. 77zip can test them too. The large one fails with unexpected end of data, the small one passes.

**Comment by McSpidey** [comment]
I've been testing more samples and the size doesn't seem to be a factor. I've now found files over 100MB that test fine and a file under 2MB that fails both with rust-cfb and 7zip, but loads fine in 3dsmax and works if It tufn off this exceptions. I think it's going to be about how the files are made.

New sample:
1.16 MB (1,221,866 bytes)

Streams (via 7zip):
![image](https://user-images.githubusercontent.com/1709573/57311993-0a7f6200-7130-11e9-9aad-ed8d13ae57b9.png)

Error:
Malformed FAT (FAT has 298 entries, but file has only 297 sectors)

**Comment by mdsteele** [comment]
> CFB total file size (from windows explorer properties)
> 101 MB (106,705,932 bytes)

> Stream size as seen from your rust-cfb's length (I'll need to find or make another external tool to verify this)
> stream.len() = 25612.

Great, thanks.  There are two possible sector sizes for a CFB file (512 and 4096), but a CFB file that large is most likely using the larger, 4096-byte sector size.

```
106705932 % 4096 = 1036
    25612 % 4096 = 1036
```

So yep, that seems to suggest that my hypothesis was correct: the first 1036 bytes of that final sector (that is, the only bytes that contain meaningful data) are indeed present in the file, it's just that the file wasn't padded out to contain the (empty) remainder of that sector.  That would explain why `rust-cfb` was able to read the stream just fine once you commented out the relevant asserts.

Spec aside, this is obviously a thing that some implementations do, so it'd be nice if `rust-cfb` could read those files.  Although, if I understand your last comment correctly, it sounds like 7zip rejects the file that `rust-cfb` is currently failing on?

**Comment by mdsteele** [comment]
On the 1.1 MB file, we again have:

```
1221866 % 4096 = 1258
  13546 % 4096 = 1258
```

(13,546 being the size of the FileAssetMetaData3 stream in that file, which was also the problem stream for the 101 MB file.)

**Comment by mdsteele** [comment]
Since some other implementations (e.g. 3dsmax) create files with incomplete final sectors, seems like `rust-cfb` should allow that when reading.  And since some other implementations (e.g. 7zip) reject files with incomplete final sectors, seems like `rust-cfb` should always pad out sectors when writing (which is what it already does).

**Comment by McSpidey** [comment]
Nice work!

**Comment by mdsteele** [comment]
Okay, I've just pushed a change (da7f828) that I hope will fix it.  Can you give it a try?

**Comment by McSpidey** [comment]
Confirmed, the new version can read and parse the stream without errors. Thanks so much!


I'll be working on write testing next so will see how that goes, but for now I just tried my old test of seeing what happens by pushing the stream length up and back down with no other changes.

// Size change test
let test_len = stream.len();
stream.set_len(test_len+4096).unwrap();
stream.set_len(test_len).unwrap();

Unsuprisingly it had bad results.
On a normally padded file that produced no 7zip errors reading had this error.
thread 'main' panicked at 'assertion failed: `(left != right)`
  left: `4294967294`,
 right: `4294967294`', libs\rust-cfb-master\src\lib.rs:411:13

Then 7zip would no longer open the file at all.

**Comment by mdsteele** [comment]
What is the value of `test_len` in the test you mention above?

The CFB format mandates that short streams (less than 4096 bytes) are stored differently than long ones (4096 bytes or more), and I think `rust-cfb` might be buggy in the case when a long stream is truncated to become short again.  If `test_len` is less than 4096, then the second `set_len()` in your test probably triggers that bug.

**Comment by McSpidey** [comment]
The stream length in this case was longer than 4096 (it was the one from above, 25612). I wouldn't read too much into this result just yet. I'll report back once I have have the new stream being generated properly, then can compare and re-test the length stream changing function.

**Comment by McSpidey** [comment]
Just wanted to pass on that changing the stream and setting the new length  seems to be working on.

I'm currently using these steps to overwrite a stream while it's still loaded.
Seeking to 0
using write-all and passing in the new databuffer
Using set_len to match the new data buffersize
then using flush.

**Comment by McSpidey** [comment]
Update: I've managed to make it stable by setting the stream length to 0, then letting the write command auto expand it instead of setting it myself.

**Comment by mdsteele** [comment]
Thanks, glad you were able to find a workaround for now until this can get fixed properly.

**Comment by a8nJ** [comment]
https://github.com/mdsteele/rust-msi/issues/3

**Comment by mdsteele** [comment]
I've just pushed commit 56ac943f2d902ce06b1bfa04896086542856b9c7, which reworks the internals of the `Stream` type in a way that should fix the case when a long stream is truncated to become short again.  (That commit also adds a bunch of new tests for stream resizing, including a large-to-small test that fails without those changes and passes with them.)
