### ISSUE TITLE
Malformed directory entry (non-null stream CLSID ...)

### ISSUE THREAD

**Issue by ikrivosheev** [mdsteele/rust-cfb#26]
Hello! Thank you for great library. I try open doc file using the library and get error: `Custom { kind: InvalidData, error: "Malformed directory entry (non-null stream CLSID: 0f000000-0400-4ef0-0000-0032000af008)" }`

[File](https://github.com/mdsteele/rust-cfb/files/8928362/qalt_attach_MODEL_O.zip).

I find: https://github.com/mdsteele/rust-cfb/blob/f12863b8e3d787975bac3771765109974e6e513b/src/internal/direntry.rs#L168

Can I remove this or is it a required check?

**Comment by ikrivosheev** [comment]
@mdsteele thank you for the fix! Can you make small fix release?

**Comment by mdsteele** [comment]
Sure, I've now published this as [v0.7.1](https://crates.io/crates/cfb/0.7.1).

**Comment by ikrivosheev** [comment]
@mdsteele thanks a lot!
