### ISSUE TITLE
Error: Malformed directory (root entry name is "\", but should be "Root Entry")

### ISSUE THREAD

**Issue by ikrivosheev** [mdsteele/rust-cfb#29]
I try open doc file using the library and get error: `Custom { kind: InvalidData, error: "Malformed directory (root entry name is \"\", but should be \"Root Entry\")" }`

File: [qalt_attach_9384.zip](https://github.com/mdsteele/rust-cfb/files/9019152/qalt_attach_9384.zip)

**Comment by mdsteele** [comment]
Thanks for the report!  The MS-CFB spec is unambiguous here: according to section 2.6.2, "The root directory entry's Name field MUST contain the null-terminated string 'Root Entry' in Unicode UTF-16."  That said, just like with issue #26 and issue #27, there's no reason we can't just ignore the incorrect value when parsing and pretend it's what it's supposed to be.  So I can make that change.

**Comment by mdsteele** [comment]
I've just published this as [v0.7.3](https://crates.io/crates/cfb/0.7.3).

**Comment by ikrivosheev** [comment]
@mdsteele awesome! Thank you very much!
