### ISSUE TITLE
Malformed FAT (FAT sector xxx is not marked as such in the FAT)

### ISSUE THREAD

**Issue by inzanez** [mdsteele/rust-cfb#30]
Hi

I am reading Microsoft MSG files and from time to time I get the message above. Reading these MSG files with MSG readers does work, so I wonder how or why that would be an issue?

A sample would be: https://www.file.io/r5AB/download/BHSIDV1A4qJU

Best regards...

**Comment by inzanez** [comment]
@mdsteele Many thanks for the quick answer! That's quite interesting. Yes, I can imagine that there are quite a lot of files out there that do not comply with the specs,...pretty much the same as for other files like RTF :-)

**Comment by ikrivosheev** [comment]
@mdsteele maybe you can report it to microsoft? To fix the RFC?
