### ISSUE TITLE
Copying / Writing CFB files

### ISSUE THREAD

**Issue by inzanez** [mdsteele/rust-cfb#33]
Hi

just noticed that copying CFB files stream by stream often results in a different file size. I tested that with Microsoft `msg` files when I realized that I could not open `msg` files written with the `rust-cfb` library.

What I have done is the following:
```

    let mut original = cfb::open("/tmp/test/outlook.msg")?;

    let mut streams = vec![];
    let mut storages = vec![];

    for e in original.read_storage("/")? {
        if original.is_stream(e.path()) {
            streams.push(e.path().to_path_buf());
        }

        if original.is_storage(e.path()) {
            storages.push(e.path().to_path_buf());
        }
    }

    let mut copy = cfb::create("/tmp/test/copy.msg")?;

    for s in storages {
        copy.create_storage_all(s)?;
    }

    let mut buf = vec![];
    for p in streams {
        let mut s = original.open_stream(&p)?;
        s.read_to_end(&mut buf)?;
        let mut s = copy.create_stream(&p)?;
        s.write(&buf)?;
        s.flush()?;
    }
```

As mentioned, there's a binary difference, which should not really be an issue I guess. But I have noticed that the resulting `copy.msg` is not readable anymore in Microsoft Outlook for instance...

**Comment by mdsteele** [comment]
Thanks for the report.  I think the code snippet you've written won't copy over the metadata on directory nodes, such as [CLSIDs](https://mdsteele.games/rust-cfb/cfb/struct.CompoundFile.html#method.set_storage_clsid) and [state bits](https://mdsteele.games/rust-cfb/cfb/struct.CompoundFile.html#method.set_state_bits).  My first guess would be that perhaps Outlook is expecting to see particular CLSIDs on some of the storage nodes?

**Comment by inzanez** [comment]
@mdsteele Oh, that's very interesting. I will have to look them up in the MSG documentation, never seen them referenced. But then that documentation is quite huge. Nevertheless, I tried copying them in the meantime:
```

    let mut original = cfb::open("/tmp/test/outlook.msg")?;
    let mut copy = cfb::create("/tmp/test/copy.msg")?;

    let mut streams = vec![];

    for e in original.read_storage("/")? {
        if original.is_stream(e.path()) {
            streams.push((e.path().to_path_buf(), e.clsid().clone(), e.state_bits()));
        }

        if original.is_storage(e.path()) {
            copy.create_storage_all(e.path())?;
            copy.set_storage_clsid(e.path(), e.clsid().clone())?;
            copy.set_state_bits(e.path(), e.state_bits())?;
        }
    }



    let mut buf = vec![];
    for (p, clsid, bits) in streams.iter() {
        let mut s = original.open_stream(p)?;
        s.read_to_end(&mut buf)?;
        let mut s = copy.create_stream(p)?;
        s.write(&buf)?;
        s.flush()?;
        drop(s);
        copy.set_state_bits(&p, *bits)?;
    }
```

Unfortunately that did not make any difference, still cannot open that file.

**Comment by mdsteele** [comment]
Hmm, I'm looking closer now and realizing that it doesn't look like your code will recurse into nested storage nodes?  I think you want to use [`walk_storage("/")`](https://docs.rs/cfb/latest/cfb/struct.CompoundFile.html#method.walk_storage) (or just [`walk()`](https://docs.rs/cfb/latest/cfb/struct.CompoundFile.html#method.walk)) instead of `read_storage("/")`.

(Also, minor aside: if you want, you can write e.g. [`e.is_storage()`](https://docs.rs/cfb/latest/cfb/struct.Entry.html#method.is_storage) instead of `original.is_storage(e.path())`.)

**Comment by inzanez** [comment]
@mdsteele Ok, I will need to check that too then :-) If there is any nested storage,...

**Comment by mdsteele** [comment]
Okay, thanks for trying.  I'm running out of ideas, though.  (-:

Do you have an example file you can share that doesn't work when duplicated via the crate?  I can take a look at it and try to figure out where the problem might be.

**Comment by inzanez** [comment]
Yes of course.

Btw. I also see that the file size is quite a bit different, wondering why that might be:

```
-rw-r--r-- 1 user1 user1 290816 Mar  9 08:43 copy.msg
-rw------- 1 user1 user1  32768 Mar  9 08:43 outlook.msg
```
`outlook.msg` is the original I attached below.

[message.zip](https://github.com/mdsteele/rust-cfb/files/10929017/message.zip)

**Comment by jtran** [comment]
Maybe this is a separate issue, but I've also noticed that copying a file with the library tends to result in a much larger file.

Could both the file size and the problem of the OP be related to the CFB format version, which can be controlled using [`create_with_version()`](http://mdsteele.games/rust-cfb/cfb/struct.CompoundFile.html#method.create_with_version)?  In theory, this is another piece of metadata that might lead to a program not being able to read a file produced from the library using the code above, if it didn't support the default version 4.

I only just noticed the version while following this thread.  And sure enough, the `outlook.msg` file uses version 3.

**Comment by inzanez** [comment]
@jtran Very interesting. I was just scanning the documentation regarding a specific CFB version. I have not found anything yet in the official microsoft documentation. I find some web-sites referring to CFB version 3 however.

I just rewrote my test to

```
  let f = std::fs::File::create("/tmp/test/copy.msg")?;
  let mut copy = cfb::CompoundFile::create_with_version(cfb::Version::V3, f)?;
```
The file size changed a bit, but not that much:
```
-rw-r--r-- 1 user1 user1 281600 Mar  9 20:37 copy.msg
-rw------- 1 user1 user1  32768 Mar  9 20:25 outlook.msg
```

When opening that file with Outlook, I do get a funny error: `We can't open 'file_location.msg'. It's possible the file is already open, or you don't have permission to open it.`

It is interesting and I guess helpful to know that MSG files might need to be CFB version 3 nevertheless.

**Comment by mdsteele** [comment]
That larger file size on the duplicate (even when using `Version::V3`) is very mysterious.  I tried doing a similar thing, and got a file with a similar size:

```
-rw-------@ 1 mdsteele  staff  32768 Mar  9 08:43 outlook.msg
-rw-r--r--  1 mdsteele  staff  31744 Mar 19 18:59 duplicate.msg
````

Here's the code I used:

```rust
    let mut original = cfb::open(in_path)?;
    let version = original.version();
    let out_file = std::fs::OpenOptions::new()
        .read(true)
        .write(true)
        .create(true)
        .truncate(true)
        .open(out_path)?;
    let mut duplicate = cfb::CompoundFile::create_with_version(version, out_file)?;
    let mut stream_paths = Vec::<std::path::PathBuf>::new();
    for entry in original.walk() {
        if entry.is_storage() {
            if !entry.is_root()	{
                duplicate.create_storage(entry.path())?;
            }
            duplicate.set_storage_clsid(entry.path(), entry.clsid().clone())?;
        } else {
            stream_paths.push(entry.path().to_path_buf());
	}
    }
    for path in stream_paths.iter() {
        std::io::copy(&mut original.open_stream(path)?,
                      &mut duplicate.create_new_stream(path)?)?;
    }
```

(Note that this is with the HEAD version of the crate.  I don't _think_ it should differ significantly from v0.7.3, though?)

Here's the resulting file: [duplicate.msg.zip](https://github.com/mdsteele/rust-cfb/files/11012544/duplicate.msg.zip).  Can you check if it works?

**Comment by inzanez** [comment]
@mdsteele Hm, this is really interesting. I am afraid I haven't had the time to play more with this yet, but I just quickly tested the file you uploaded and I do get the same error message: `It's possible the file is already open, or you don't have permission to open it.`.
Rather weird.
