### ISSUE TITLE
Tests fail on 32-bit architectures

### ISSUE THREAD

**Issue by davide125** [mdsteele/rust-cfb#4]
While trying to package rust-cfb for Fedora I've hit various test failures on 32-bit architectures:
- armv7hl: https://koji.fedoraproject.org/koji/taskinfo?taskID=67574561
- i686: https://koji.fedoraproject.org/koji/taskinfo?taskID=67574562

You can see the full output by opening link to build.log at the end of those pages. A bunch of these are overflows, so I'm not sure if it's just the tests that need to be updated or if something needs to be fixed in the library itself.

**Comment by mdsteele** [comment]
Thanks for catching this.  I just pushed commit 9ee68b670251ebbd0240b4f016244e6f47b200bd, which reworks the timestamp calculations to avoid overflowing `SystemTime` on systems where the underlying type lacks the range to represent the CFB epoch (January 1, 1601 UTC).

With those changes, all the tests are now passing for me on 32-bit Ubuntu, so I'm going to go ahead and close this bug, but please do reopen if you hit any more test failures.
