### ISSUE TITLE
Corrupted file / Paths disappear when reading using ole32.dll after copy

### ISSUE THREAD

**Issue by francisdb** [mdsteele/rust-cfb#52]
I took the code from https://github.com/mdsteele/rust-cfb/issues/33#issuecomment-1475431426 to copy this cfb file:

https://github.com/mpcarr/aztec-quest/blob/fdf371ff7f792a46fedd987ef167491dde141a18/aztecquest-dev.vpx

When reading the copied file using windows `ole32.dll` most paths can no longer be found / read. The file size however seems to be about the same. Reading the file using `rust-cfb` still works.

This is the C# project that came up with below listing:
https://github.com/francisdb/ole32-cfb-list

```
================= Original ====================
Opening storage at c:\Users\franc\RustroverProjects\aztec-quest\aztecquest-dev.vpx
root\GameStg
root\GameStg\MAC
root\GameStg\Image0
root\GameStg\Image1
root\GameStg\Image2
root\GameStg\Image3
root\GameStg\Sound0
...
root\GameStg\Sound277
root\GameStg\GameItem0
...
root\GameStg\GameItem322
root\GameStg\Collection10
root\GameStg\Collection11
root\GameStg\Collection12
root\GameStg\Collection13
root\GameStg\Collection14
root\GameStg\Collection15
root\GameStg\Collection16
root\GameStg\Collection17
root\GameStg\Collection18
root\GameStg\CustomInfoTags
root\TableInfo
root\TableInfo\TableName
root\TableInfo\AuthorName
root\TableInfo\TableSaveRev
root\TableInfo\TableVersion
root\TableInfo\TableSaveDate
================= Copy ========================
Opening storage at c:\Users\franc\RustroverProjects\aztec-quest\aztecquest-copy.vpx
root\GameStg
root\GameStg\MAC
root\GameStg\Image0
root\GameStg\Image1
root\GameStg\Image2
root\GameStg\Image3
root\GameStg\Sound0
root\GameStg\Sound1
root\GameStg\Sound2
root\GameStg\Sound3
root\GameStg\Sound4
root\GameStg\Sound5
root\GameStg\Sound6
root\GameStg\Sound7
root\GameStg\Sound8
root\GameStg\Sound9
root\GameStg\Sound10
root\GameStg\Sound11
root\GameStg\Sound12
root\GameStg\Sound13
root\GameStg\Sound14
root\GameStg\Sound15
root\GameStg\Sound16
root\GameStg\Sound17
root\GameStg\Sound18
root\GameStg\Sound19
root\GameStg\Sound20
root\GameStg\Sound21
root\GameStg\Sound22
root\GameStg\Sound23
root\TableInfo
```

### Observations
* When on copy filtering out for example the Sound items the listing is again truncated to about the same length. So it's probably not a specific item that is causing further streams to be be found.
* When trying to read one of the unlisted streams I get this:
  `Exception has occurred: CLR/System.Runtime.InteropServices.COMException
An unhandled exception of type 'System.Runtime.InteropServices.COMException' occurred in ConsoleApp1.dll: 'The docfile has been corrupted. (0x80030109)'`
* wine ole32.dll has no issues reading the copied file
* even if the streams are very small this fails
* **only the first 32 items are found (including root/storages)**

**Comment by francisdb** [comment]
@mdsteele how do I start debugging this, do you have some internal structure diff tool I could use that shows the difference between both files?

**Comment by mdsteele** [comment]
Sorry, I don't have any special tools beyond `examples/cfbtool`.  I usually debug by just adding a bunch of `println!`s to the library for whatever I'm investigating, and then running `cargo run --example cfbtool -- ls path/to/file` to make the library load the CFB file and trigger my `println!`s.

**Comment by francisdb** [comment]
This is the minimal reproducer

```rust
let minimal_path = Path::new(r"minimal.cfb");
    let file = std::fs::OpenOptions::new()
        .read(true)
        .write(true)
        .create(true)
        .truncate(true)
        .open(minimal_path)?;
    let mut cfb = CompoundFile::create(file)?;
    for i in 0..32 {
        let path = format!("stream{}", i);
        let path = Path::new(&path);
        cfb.create_stream(path)?;
    }
```

Trying to read stream `Stream31` or any non-existing stream on windows gives me
```
Exception thrown: 'System.Runtime.InteropServices.COMException' in ConsoleApp1.dll
Error: The docfile has been corrupted. (0x80030109)
``` 
With a file created by windows you get this error when reading a non-existing stream
```
Exception thrown: 'System.Runtime.InteropServices.COMException' in ConsoleApp1.dll
Error:  could not be found. (0x80030002 (STG_E_FILENOTFOUND))
```

**Comment by francisdb** [comment]
I found the issue. `num_dir_sectors` is not being updated in the header when a second sector is added. Also that value is not used for reading, the chain is just followed where ole32 probably stops reading and reports corruption. Working on a test and fix.

**Comment by mdsteele** [comment]
Thanks for tracking this down!

**Comment by francisdb** [comment]
All thanks go to you for coming up with this lib! Couldn't have build vpxtool without it.
